version: '3.5'
services:
  mongo_prod:
    container_name: perso_mongo_prod
    build: mongo/
    restart: always
    volumes:
      - ./storage/db/prod:/data/db
    environment:
      - ENV=prod
    networks:
      - prod
  node_prod:
    container_name: perso_node_prod
    build: node/
    restart: always
    volumes:
      - "./storage/node/prod:/app/storage"
    environment:
      - ENV=prod
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - MONGO_URI=mongodb://perso_mongo_prod
    networks:
      - prod
networks:
  prod:
    external:
      name: prod
