version: '3.5'
services:
  mongo_test:
    container_name: perso_mongo_test
    build: mongo/
    volumes:
      - ./mongo/mongo_data/test:/data/db
    networks:
      - test
  mongo_express_test:
    container_name: perso_mongo_express_test
    build: mongo_express/
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_test
    ports:
      - 9081:8081
    networks:
      - test
  node_test:
    container_name: perso_node_test
    build: node/
    environment:
      - ENV=test
    ports:
      - 81:80
    volumes:
      - "./storage:/app/storage"
    networks:
      - test
networks:
  test:
    external:
      name: test
