version: '3'
services:
  mongo_prod:
    container_name: perso_mongo_prod
    build: mongo/
    restart: always
    volumes:
      - ./mongo/mongo_data/prod:/data/db
    networks:
      - prod
  mongo_express_prod:
    container_name: perso_express_prod
    build: mongo_express/
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_prod
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    ports:
      - 9080:8081
    networks:
      - prod
  node_prod:
    container_name: perso_node_prod
    build: node/
    restart: always
    environment:
      - ENV=prod
      - USERNAME=${MONGO_EXPRESS_USER}
      - PASSWORD=${MONGO_EXPRESS_PASSWORD}
    ports:
      - 443:443
      - 80:80
    networks:
      - prod
networks:
  prod:
    driver: bridge
