version: '3'
services:
  mongo_test:
    container_name: perso_mongo_test
    build: mongo/
    volumes:
      - ./mongo/mongo_data/test:/data/db
    networks:
      - test
  mongo_express_test:
    container_name: perso_mongo_express_test
    build: mongo_express/
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_test
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USER_TEST}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD_TEST}
    ports:
      - 9081:8081
    networks:
      - test
  node_test:
    container_name: perso_node_test
    build: node/
    environment:
      - ENV=test
      - USERNAME=${MONGO_EXPRESS_USER_TEST}
      - PASSWORD=${MONGO_EXPRESS_PASSWORD_TEST}
    ports:
      - 81:80
    networks:
      - test
networks:
  test:
    driver: bridge