version: '3.5'
services:
  mongo_test:
    container_name: perso_mongo_test
    build: mongo/
    volumes:
      - ./storage/db/test:/data/db
    environment:
      - ENV=test
    networks:
      - test
  node_test:
    container_name: perso_node_test
    build: node/
    environment:
      - ENV=test
      - MONGO_URI=mongodb://perso_mongo_test
    ports:
      - 80:80
    volumes:
      - "./storage/node/test:/app/storage"
    networks:
      - test
networks:
  test:
    external:
      name: test
