version: '3.5'
services:
  node_prod:
    container_name: perso_node_prod
    build: node/
    restart: always
    environment:
      - ENV=prod
      - USERNAME=${USER}
      - PASSWORD=${PASSWORD}
      - MONGO_URI=mongodb://mongo_prod
    networks:
      - prod
networks:
  prod:
    external:
      name: prod
